# -*- coding: utf-8 -*-
"""737002453_ProjectCheckpoint2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSF8YwfdkDyuxJLRHLCVb9_Gj6zm97WK

# Project Checkpoint 2: Research Question Formation

**Dataset:** Goodreads Reviews – Comics & Graphic

**Goal:** Define three research questions grounded in exploratory data analysis (EDA) findings — at least two using course techniques (e.g., frequent itemset mining, text analysis) and at least one using an external technique (e.g., sequential pattern mining) — and validate feasibility through additional EDA and initial method experimentation.

The dataset consists of user reviews, ratings, timestamps, and textual feedback for books in the comics and graphic novels category. Prior EDA revealed key characteristics such as rating skewness (majority high ratings), sparse co-occurrence between items, varying user basket sizes, and meaningful temporal gaps in user activity.

All algorithmic decisions are justified based on these data properties, and methods are evaluated using appropriate metrics (e.g., support, confidence, lift, and pattern quality).

## 1. Project Scope

### Dataset

| Field | Detail |
|-------|--------|
| Dataset | Goodreads Reviews – Comics & Graphic (UCSD Book Graph) |
| Total rows analyzed | 542,338|
| Columns | 11 |
| Unique users | 59,347 |
| Unique books | 89,311 |
| Data type | User-item interactions with text reviews and metadata |
| Core fields | `user_id`, `book_id`, `rating`, `review_text` |
| Additional fields | `review_id`, `date_added`, `date_updated`, `read_at`, `started_at`, `n_votes`, `n_comments` |
| Data structure | Implicit baskets (user → set of reviewed books) + text corpus |
| Temporal component | Available via `date_added`, `date_updated`, `read_at`, and `started_at`, though `read_at` and `started_at` have substantial missingness |

### Key EDA Findings

| Finding | Value | Impact on design |
|---------|-------|-----------------|
| Dataset scale | 542,338 reviews, 59,347 users, 89,311 books | Sufficient size to support statistically meaningful pattern mining and text analysis |
| Rating skew | 65.86% of ratings are 4–5 | Weak signal for predictive modeling; motivates pattern-based and descriptive analysis instead |
| Co-occurrence sparsity | 0.9897 (≈99% sparse) | Frequent itemset mining requires careful support threshold tuning to avoid empty or trivial patterns |
| Basket size distribution | Mean = 9.14, median = 2, 95th percentile = 33 | Users have meaningful but skewed interaction sizes, enabling itemset mining while requiring handling of heavy users |
| Popularity imbalance | Few books dominate co-occurrence counts | Risk of trivial frequent patterns; motivates filtering or lift-based evaluation |
| Review length variability | Wide distribution; ~5.48% very short (≤3 tokens) | Supports text mining but requires filtering of low-information reviews |
| Missing review text | ~0.06% | Text-based methods are feasible with minimal data loss |
| Vocabulary richness | High diversity in review text | Justifies use of TF-IDF and advanced text representations |
| Temporal coverage | Timestamp fields available (`date_added`, `read_at`, `started_at`) | Enables temporal or sequential analysis |
| Temporal missingness | 61.39% (`started_at`), 69.97% (`read_at`) missing | Sequential methods must operate on filtered subsets |
| Duplicate records | None observed | No deduplication required |



### Technique Map

| Technique | Type | Course Reference | Addresses |
|-----------|------|------------------|-----------|
| Frequent Itemset Mining (Apriori / FP-Growth) | **Course** | Week 2 | RQ1 |
| Text Mining (TF-IDF / Similarity / Clustering) | **Course** | Week 7 | RQ2 |
| Topic Modeling (LDA or similar) | **External** | Not explicitly covered in syllabus | RQ3 |

## 2. Research Question Definition

### RQ1 — Frequent Itemset Mining (Course Technique)

**What frequent co-occurring book sets emerge under varying support thresholds, and how do support, confidence, and lift compare in identifying meaningful associations?**

| Attribute | Detail |
|-----------|--------|
| Task type | Frequent itemset mining + association rule mining |
| Algorithm | Apriori / FP-Growth |
| Evaluation | Support, confidence, lift; number of rules generated; interpretability of top rules |
| Motivation | EDA shows extreme co-occurrence sparsity (~0.9897) and heavy-tailed item popularity. This requires careful support tuning and motivates the use of lift to avoid dominance by popular books. Basket size variability (mean = 9.14) ensures sufficient co-occurrence signal for mining meaningful patterns. |

---

### RQ2 — Text Mining & Similarity (Course Technique)

**How effectively can TF-IDF representations capture semantic similarity between reviews, and can clustering reveal coherent groups of user preferences?**

| Attribute | Detail |
|-----------|--------|
| Task type | Text representation + clustering / similarity analysis |
| Algorithm | TF-IDF vectorization + cosine similarity / K-Means clustering |
| Evaluation | Cluster coherence (qualitative), intra-cluster similarity vs. inter-cluster distance, top terms per cluster |
| Motivation | EDA shows high lexical diversity and wide variation in review length, with only ~0.06% missing text. TF-IDF is well-suited to handle long-tail vocabularies and downweight frequent tokens. Filtering very short reviews (~5.48%) improves signal quality for clustering. |

---

### RQ3 — Topic Modeling (External Technique)

**Can topic modeling (LDA) uncover latent themes in user reviews that are not captured by surface-level TF-IDF representations?**

| Attribute | Detail |
|-----------|--------|
| Task type | Unsupervised topic modeling (external technique) |
| Algorithm | Latent Dirichlet Allocation (LDA) |
| Evaluation | Topic coherence score, interpretability of top words per topic, diversity of topics |
| Motivation | EDA highlights rich, diverse textual data with long-tail vocabulary distributions. TF-IDF captures surface-level term importance, but does not model latent semantic structure. LDA enables discovery of hidden themes (e.g., genre preferences, writing style, sentiment patterns), providing deeper insight beyond bag-of-words representations. |

---

### RQ-to-method mapping table

| RQ | Task type | Course / External | Algorithm | Primary metric | Secondary metrics |
|----|-----------|-------------------|-----------|---------------|------------------|
| RQ1 | Itemset + rule mining | **Course** | Apriori / FP-Growth | Support / Lift | Confidence, rule count |
| RQ2 | Text similarity / clustering | **Course** | TF-IDF + K-Means | Cluster coherence | Similarity scores |
| RQ3 | Topic modeling | **External** | LDA | Topic coherence | Topic diversity, interpretability |

## 3. Motivation and Feasibility

### Data-Driven Motivation

| RQ | EDA evidence | Why this method |
|----|-------------|-----------------|
| RQ1 | Co-occurrence sparsity is extremely high (0.9897) and basket sizes vary (mean = 9.14, median = 2) | Frequent itemset mining is suitable for discovering hidden co-occurrence patterns in sparse transactional data. Lift is necessary to correct for heavy-tailed popularity and avoid trivial frequent patterns. |
| RQ2 | High lexical diversity with long-tail vocabulary and only ~0.06% missing text | TF-IDF downweights common terms and highlights informative tokens, enabling meaningful similarity computation and clustering despite noisy and sparse text data. |
| RQ3 | Rich free-text reviews with diverse vocabulary and varying lengths | Topic modeling (LDA) captures latent semantic structure beyond TF-IDF, enabling discovery of hidden themes such as genres, writing style, and user preferences. |

---

### Non-Triviality

- **RQ1 vs naive co-occurrence:** Due to extreme sparsity and popularity skew, naive frequency counts would primarily surface popular books. Evaluating rules using lift ensures that discovered patterns represent meaningful associations rather than popularity bias.

- **RQ2 vs raw text similarity:** Direct comparison of raw text is ineffective due to high dimensionality and noise. TF-IDF introduces weighting that reduces the influence of frequent tokens, making similarity and clustering more meaningful.

- **RQ3 vs TF-IDF:** TF-IDF captures surface-level importance but ignores latent semantic structure. LDA models documents as mixtures of topics, enabling deeper insights into hidden thematic patterns.

---

### Feasibility Assessment

| RQ | Environment | Runtime | Memory | Data Scope | Status |
|----|-------------|---------|--------|------------|--------|
| RQ1 | CPU (local) | Moderate (depends on support threshold) | < 2 GB | All users with ≥2 books | ✓ Confirmed |
| RQ2 | CPU (local) | Fast (few minutes) | < 4 GB | All reviews (excluding very short ones) | ✓ Confirmed |
| RQ3 | Colab GPU (optional) | Faster convergence on sampled data | ~4 GB (CPU/GPU) | Sample of ~20k–30k reviews | ✓ Confirmed |

RQ3 (LDA) can be executed on CPU; however, GPU-enabled environments (e.g., Google Colab) can accelerate training when using larger samples or multiple topic sweeps.

---

### Risks and Mitigations

| RQ | Risk | Mitigation | Outcome |
|----|------|-----------|---------|
| RQ1 | High sparsity → few or trivial itemsets | Tune support thresholds; filter users with small baskets | ✓ Ensures meaningful patterns |
| RQ2 | Noise from short reviews | Remove reviews with ≤3 tokens | ✓ Improves clustering quality |
| RQ3 | Computational cost and unstable topics | Sample 20k–30k reviews; tune number of topics (k) | ✓ Stable and interpretable topics |

## 4. Setup and Imports
"""

# =========================
# 1. Setup & Imports
# =========================

# Core
import pandas as pd
import numpy as np

# File handling (for streaming JSON)
import gzip
import json
from urllib.request import urlopen

# Combinatorics & counting (EDA)
from itertools import combinations
from collections import Counter

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# Text processing
from sklearn.feature_extraction.text import TfidfVectorizer

# Clustering & similarity
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity

# Topic modeling
from sklearn.decomposition import LatentDirichletAllocation

# Itemset mining
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder


# Misc
import warnings
warnings.filterwarnings("ignore")

print("All libraries imported successfully.")

"""## 5. Data Loading and Cleaning"""

# =========================
# 2. Data Loading
# =========================

DATA_PATH = "goodreads_reviews_comics_graphic.json.gz"
rows = []

with gzip.open(DATA_PATH, "rt", encoding="utf-8") as f:
    for line in f:
        rows.append(json.loads(line))

df = pd.DataFrame(rows)

print("Dataset loaded successfully.\n")
print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")


display(df.head(3))
display(df.info())

# =========================
# 3. Data Cleaning & Preprocessing
# =========================

# --- 1. Drop rows with missing critical identifiers ---
# Required for itemset mining (RQ1)
df = df.dropna(subset=["user_id", "book_id"]).copy()

# --- 2. Handle review text ---
# Required for RQ2 (TF-IDF) and RQ3 (LDA)
df["review_text"] = df["review_text"].fillna("").astype(str).str.strip()

# --- 3. Convert numeric fields ---
numeric_cols = ["rating", "n_votes", "n_comments"]
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Keep valid ratings only (1–5)
if "rating" in df.columns:
    df = df[df["rating"].between(1, 5, inclusive="both")]
    df["rating"] = df["rating"].astype(int)

# --- 4. Convert timestamps ---
date_cols = ["date_added", "date_updated", "read_at", "started_at"]
for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

# --- 5. Create review length feature ---
df["review_len_tokens"] = df["review_text"].str.split().str.len()

# --- 6. Remove very short reviews (noise) ---
# Helps RQ2 (clustering) and RQ3 (LDA)
df = df[df["review_len_tokens"] > 3]

# --- 7. Check duplicates ---
duplicates = df.duplicated().sum()

# --- Final summary ---
print("Data cleaning completed.\n")

print(f"Final shape: {df.shape}")
print(f"Duplicate rows: {duplicates}")

print("\nMissing values (key columns):")
print(df[["user_id", "book_id", "review_text", "rating"]].isna().sum())

"""###  6. Exploratory Data Analysis

To support the proposed research questions, we perform a small set of targeted exploratory checks beyond Checkpoint 1.

- **RQ1 (Frequent Itemsets):** We examine basket-size feasibility and item popularity skew to confirm that enough users have multi-book interactions and to assess whether frequent patterns may be dominated by a few highly popular books.
- **RQ2 (TF-IDF + Clustering):** We inspect review-length statistics to verify that the text contains enough signal for meaningful vectorization and clustering.
- **RQ3 (LDA):** We evaluate vocabulary richness and non-empty text availability to confirm that topic modeling is practical, while also estimating a reasonable sample size for efficient experimentation.

These checks are intended to justify method choice, confirm feasibility, and guide parameter decisions such as basket filtering, short-review removal, and LDA sampling size.

### EDA 1: Basket Size Feasibility (RQ1)

I analyze the distribution of the number of books reviewed per user (basket size) to ensure that frequent itemset mining is feasible.

Users with multiple interactions are required to generate meaningful co-occurrence patterns. This analysis helps determine whether filtering (e.g., users with ≥2 or ≥5 books) is necessary.
"""

basket_sizes = df.groupby("user_id")["book_id"].nunique()

print("Basket size statistics:")
print(basket_sizes.describe())

print("\nUsers with >=2 books:", (basket_sizes >= 2).sum())
print("Users with >=5 books:", (basket_sizes >= 5).sum())

plt.hist(basket_sizes, bins=50)
plt.title("Basket Size Distribution")
plt.xlabel("Number of Books per User")
plt.ylabel("Count")
plt.show()

"""### EDA 2: Item Popularity Distribution (RQ1)

I examine the most frequently reviewed books to understand whether item popularity is skewed.

A heavy-tailed distribution indicates that a small number of books dominate interactions, which can bias frequent itemsets. This motivates the use of lift in association rule evaluation.
"""

top_books = df["book_id"].value_counts().head(10)

print("Top 10 most reviewed books:")
print(top_books)

top_books.plot(kind="bar")
plt.title("Top 10 Most Popular Books")
plt.xlabel("Book ID")
plt.ylabel("Review Count")
plt.show()

"""### EDA 3: Review Length Analysis (RQ2)

I analyze review length to assess text quality for TF-IDF and clustering.

Very short reviews may lack meaningful information, while longer reviews provide richer context. This helps justify filtering short reviews before text modeling.
"""

print("Review length statistics:")
print(df["review_len_tokens"].describe())

print("\n% short reviews (<=3 tokens):",
      (df["review_len_tokens"] <= 3).mean() * 100)

print("% long reviews (>50 tokens):",
      (df["review_len_tokens"] > 50).mean() * 100)

plt.hist(df["review_len_tokens"], bins=50)
plt.title("Review Length Distribution")
plt.xlabel("Number of Tokens")
plt.ylabel("Count")
plt.show()

"""### EDA 4: Vocabulary Richness (RQ2 & RQ3)

I analyze the diversity of words in the review text to understand vocabulary distribution.

A high proportion of rare words indicates a long-tail distribution, which supports the use of TF-IDF and motivates topic modeling approaches like LDA.
"""

all_words = " ".join(df["review_text"]).split()
word_counts = Counter(all_words)

rare_words = sum(1 for w, c in word_counts.items() if c < 5)

print("Total unique words:", len(word_counts))
print("Rare words (<5 occurrences):", rare_words)
print("Rare word percentage:",
      (rare_words / len(word_counts)) * 100)

"""### EDA 5: Topic Modeling Feasibility (RQ3)

I verify that sufficient non-empty review text exists for topic modeling.

This analysis ensures that LDA can be applied effectively and helps determine a reasonable sample size for efficient computation.
"""

non_empty = (df["review_text"].str.strip() != "").sum()

print("Non-empty reviews:", non_empty)
print("Total rows:", len(df))

print("Usable for LDA (%):",
      (non_empty / len(df)) * 100)

print("Recommended sample size:",
      min(30000, len(df)))

"""## 7. Methodological Planning

### Data Usage Strategy

Since all research questions are unsupervised, I do not use a train/validation split.

| Decision | Choice | Why this decision was made |
|----------|--------|----------------------------|
| Train/test split | Not used | All tasks are unsupervised (itemsets, clustering, LDA), so predictive evaluation is not required |
| Full dataset usage | Yes (where feasible) | Using more data improves pattern coverage and stability for unsupervised methods |
| Subsampling (RQ3) | 20k–30k reviews | EDA shows large dataset size; full LDA is computationally expensive, while sampling preserves diversity |
| Random seed | 42 | Ensures reproducibility of clustering and sampling |

---

### Method Plan by Research Question

| RQ | Algorithm | Decision | Why this decision was made |
|----|----------|----------|----------------------------|
| RQ1 | FP-Growth (primary), Apriori (optional) | Prefer FP-Growth | EDA shows large dataset and high sparsity; FP-Growth is more efficient than Apriori |
| RQ2 | TF-IDF + K-Means | Use TF-IDF representation | EDA shows high lexical diversity and long-tail vocabulary; TF-IDF downweights frequent tokens |
| RQ3 | LDA | Use probabilistic topic modeling | EDA shows rich text with latent themes not captured by TF-IDF |

---

### Evaluation Framework

| RQ | Metric | Why this metric was chosen |
|----|--------|---------------------------|
| RQ1 | Support, confidence, lift | Lift corrects for heavy-tailed popularity observed in EDA; support alone would bias toward popular books |
| RQ2 | Cluster coherence, similarity | Clustering is unsupervised; semantic coherence is more meaningful than accuracy |
| RQ3 | Topic coherence | Topic modeling is evaluated by interpretability and coherence rather than prediction |

---

### Algorithmic Decisions and Justifications

| Decision | Value | Why this decision was made |
|----------|-------|----------------------------|
| Basket filtering (RQ1) | Keep users with ≥2 books | EDA shows many users have small baskets; users with 1 book cannot form itemsets |
| Itemset size limit | Max size = 3 | EDA shows extreme sparsity (0.9897); larger itemsets become too rare and uninterpretable |
| Support thresholds | 0.005, 0.01, 0.02 | EDA indicates sparse co-occurrence; multiple thresholds ensure non-trivial patterns |
| Use lift | Yes | EDA shows popularity skew; lift removes bias toward frequent items |
| Remove short reviews | review_len_tokens > 3 | EDA shows ~5.48% very short reviews; these add noise to text models |
| TF-IDF feature limit | Top 5k–10k terms | EDA shows long-tail vocabulary; limiting features reduces noise and improves efficiency |
| K-Means cluster range | k = 5, 8, 10 | True number of clusters unknown; must explore multiple values |
| LDA topic range | k = 5, 10, 15 | Topic count is not known a priori; multiple values ensure meaningful topics |
| LDA sampling | 20k–30k reviews | Full dataset is large; sampling balances computational cost and topic stability |

---

### Baselines

| RQ | Baseline | Why this baseline was chosen |
|----|----------|-----------------------------|
| RQ1 | High-support-only patterns | Shows whether lift adds value beyond raw frequency |
| RQ2 | TF-IDF similarity without clustering | Helps compare structured clustering vs raw similarity |
| RQ3 | TF-IDF keyword extraction | Provides comparison between surface-level tokens and latent topics |

---

### Initial Feasibility Runs

| RQ | Initial run | Why this was performed |
|----|-------------|------------------------|
| RQ1 | FP-Growth on filtered baskets | Ensures transaction encoding works and support thresholds are valid |
| RQ2 | TF-IDF + small K-Means run | Confirms vectorization and cluster interpretability |
| RQ3 | LDA on small subset (~5k) | Ensures preprocessing works and topics are meaningful before scaling |

---

### Reproducibility Plan

| Decision | Why this decision was made |
|----------|----------------------------|
| Fixed random seed | Ensures consistent results across runs |
| Modular notebook structure | Improves readability and reproducibility |
| Explicit parameter reporting | Required for transparency and grading |
| Representative outputs | Helps validate correctness and interpretability |

### RQ1 Feasibility: Frequent Itemset Mining

I perform a preliminary run of FP-Growth on a subset of user baskets to verify that:

- Transaction encoding works correctly
- Support thresholds produce non-empty itemsets
- Association rules can be generated

This ensures that frequent itemset mining is feasible given the dataset’s sparsity and basket structure.
"""

print("===== RQ1: FP-Growth Feasibility =====")

basket_df = (
    df.groupby("user_id")["book_id"]
      .apply(lambda x: sorted(set(x)))
      .reset_index(name="books")
)

basket_df = basket_df[basket_df["books"].str.len() >= 2]

basket_sample = basket_df.sample(
    n=min(2000, len(basket_df)),
    random_state=42
)

transactions = basket_sample["books"].tolist()

te = TransactionEncoder()
txn_matrix = pd.DataFrame(
    te.fit(transactions).transform(transactions),
    columns=te.columns_
)

itemsets = fpgrowth(txn_matrix, min_support=0.01, use_colnames=True)

print(f"Transactions used: {len(transactions):,}")
print(f"Unique items: {txn_matrix.shape[1]:,}")
print(f"Frequent itemsets found: {len(itemsets):,}")

# Show top itemsets
if not itemsets.empty:
    print("\nTop frequent itemsets:")
    display(itemsets.sort_values("support", ascending=False).head(5))

# Assertions
assert len(transactions) > 0
assert txn_matrix.shape[1] > 0
assert not itemsets.empty, "No itemsets found — adjust support"

print("RQ1 feasibility passed\n")

"""### RQ2 Feasibility: TF-IDF and Clustering

I run TF-IDF vectorization followed by a small K-Means clustering model to verify that:

- Text preprocessing is valid
- TF-IDF produces a non-empty feature space
- Clustering produces meaningful groupings

This confirms that text-based analysis is feasible for the dataset.
"""

print("===== RQ2: TF-IDF + Clustering Feasibility =====")

text_df = df[df["review_len_tokens"] > 3]

text_sample = text_df.sample(
    n=min(5000, len(text_df)),
    random_state=42
)

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=5000,
    min_df=5
)

X = vectorizer.fit_transform(text_sample["review_text"])

kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
labels = kmeans.fit_predict(X)

print(f"Documents used: {X.shape[0]:,}")
print(f"Vocabulary size: {X.shape[1]:,}")
print(f"Clusters formed: {len(set(labels))}")

# Cluster distribution table
cluster_counts = pd.Series(labels).value_counts().sort_index()
print("\nCluster distribution:")
display(cluster_counts)

# Top terms per cluster
terms = vectorizer.get_feature_names_out()
centroids = kmeans.cluster_centers_.argsort(axis=1)[:, ::-1]

print("\nTop terms per cluster:")
for i in range(3):  # show first 3 clusters
    top_terms = [terms[ind] for ind in centroids[i, :10]]
    print(f"Cluster {i}: {top_terms}")

# Assertions
assert X.shape[0] > 0
assert X.shape[1] > 0
assert len(set(labels)) == 5

print("RQ2 feasibility passed\n")

"""### RQ3 Feasibility: Topic Modeling (LDA)

I run LDA on a sampled subset of reviews to verify that:

- Text data is suitable for topic modeling
- The model converges without errors
- Topic distributions are valid probability distributions

This ensures that topic modeling is computationally feasible and produces interpretable outputs.
"""

print("===== RQ3: LDA Feasibility =====")

lda_sample = df[df["review_len_tokens"] > 3].sample(
    n=min(5000, len(df)),
    random_state=42
)

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=3000,
    min_df=5
)

X = vectorizer.fit_transform(lda_sample["review_text"])

lda = LatentDirichletAllocation(
    n_components=5,
    random_state=42
)

doc_topic = lda.fit_transform(X)

print(f"Documents used: {X.shape[0]:,}")
print(f"Vocabulary size: {X.shape[1]:,}")
print(f"Topics: {doc_topic.shape[1]}")

# Topic distribution summary
topic_distribution = pd.DataFrame(doc_topic).mean().sort_values(ascending=False)
print("\nAverage topic distribution:")
display(topic_distribution)

# Top words per topic
terms = vectorizer.get_feature_names_out()

print("\nTop words per topic:")
for i, topic in enumerate(lda.components_[:3]):
    top_idx = topic.argsort()[::-1][:10]
    top_words = [terms[j] for j in top_idx]
    print(f"Topic {i}: {top_words}")

# Assertions
assert doc_topic.shape[0] == X.shape[0]
assert doc_topic.shape[1] == 5
assert np.allclose(doc_topic.sum(axis=1), 1, atol=1e-5)

print("RQ3 feasibility passed\n")

"""## Collaboration Declaration

On my honor, I declare the following resources were used in this work:

1. **Collaborators:** None

2. **Web Sources:**
    - Goodreads Reviews Dataset (UCSD Book Graph): https://mcauleylab.ucsd.edu:8443/public_datasets/gdrive/goodreads/byGenre/goodreads_reviews_comics_graphic.json.gz  
    - scikit-learn documentation: https://scikit-learn.org/  
    - mlxtend documentation (frequent pattern mining): http://rasbt.github.io/mlxtend/   
    - scikit-learn Topic Modeling (LDA): https://scikit-learn.org/stable/modules/decomposition.html#latentdirichletallocation  
    - Gensim Topic Modeling Tutorial: https://radimrehurek.com/gensim/auto_examples/core/run_topics_and_transformations.html  
    - Stanford Topic Modeling Toolbox: https://nlp.stanford.edu/software/tmt/tmt-0.4/  
    - Towards Data Science – LDA Explanation: https://towardsdatascience.com/latent-dirichlet-allocation-lda-9d1cd064ffa2  
    - Analytics Vidhya – Topic Modeling Guide: https://www.analyticsvidhya.com/blog/2018/10/mining-online-reviews-topic-modeling-lda/  

3. **AI Tools:**
   ChatGPT (OpenAI) was used to assist with structuring research questions, refining methodological planning, generating code templates, improving documentation clarity, and debugging implementation details related to FP-Growth, TF-IDF, clustering, and LDA.

4. **Citations:**
   - Pérez-Ortega, J., Almanza-Ortega, N. N., Vega-Villalobos, A., et al. (2019). *The K-Means Algorithm Evolution.* :contentReference[oaicite:0]{index=0}  
   - Sheng, Y. (2024). *Augmenting K-Means Clustering With Qualitative Data.* :contentReference[oaicite:1]{index=1}  
   - Nugroho, S. A., Bachtiar, F. A., & Wihandika, R. C. (2022). *Aspect Extraction in E-Commerce Using LDA with TF-IDF.* :contentReference[oaicite:2]{index=2}  
   - Pokharel, M., Bhatta, J., & Paudel, N. (2021). *Comparative Analysis of K-Means Algorithms for Clustering.* :contentReference[oaicite:3]{index=3}  
   - Chakraborty, J., Pradhan, D. K., & Nandi, S. (2023). *Multiple K-Means Cluster Ensemble Framework.*  
   - Blei, D. M., Ng, A. Y., & Jordan, M. I. (2003). Latent Dirichlet Allocation.
"""